### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by glixx** [spiderbit/canta#30]
Needs to update dependensies with current state.

**Comment by spiderbit** [comment]
Did you get it to run? I am sorry I mostly abandoned the project so did the other commiters.

I tried to reboot it with my canta-ng project trying to use the blender engine, but the source is hard to refactor / maintain.

But if you send good patches I might consider them, or you can fork it and become the new major maintainer of it.

**Comment by glixx** [comment]
canta-ng is not interesting for packaging. blender is big dependency, wrong way. canta is the best, but dependencies are not actual.
For example, gstreamer, python have new versions. Just update code.

**Comment by spiderbit** [comment]
Well for what project you want to package it?

I think blender is not really a dependency but you export a binary from it basically. So therefor a blender version would work :D

**Comment by glixx** [comment]
Canta was packaged for Mageia Linux: https://pkgs.org/download//usr/bin/canta
blenter is requires, if you need canta-ng, then you need to install blender. So total size for installation is to big.

**Comment by spiderbit** [comment]
so there is a python 2.7 version of soya3d.

I am not sure how I am supposed to help you, can't you send me a PR? there is even a fork with a small patch I did not pull back.

I went not only away from canta to canta-ng I even left the python world for the most part since then. Can't you just run it? Did they chance the api?

I guess gstreamer api changed since then? So you have done a python project, can't you fix it? At this point it would be probably as easy for you then me. I didn't touch this code since nearly 10 years.

Heck partially I switched away from python because of this project :D

**Comment by glixx** [comment]
yes, needs to update for gstreamer first.
I don't know python.

**Comment by spiderbit** [comment]
I thought I saw a python project in your profile that is not a fork of somebody else.
But I have here not a good linux setup to test it.

Could you give me the first message you get that fails? And maybe I can help you fix this. The biggest problem seems to me the gst situation, but I think there is not that much that has chanced in the api at least at a quick look:

canta/canta/event/input_gstreamer.py
http://brettviren.github.io/pygst-tutorial-org/pygst-tutorial.html

You would need to add that to the top as import statements.

gi.require_version('Gst', '1.0')
from gi.repository import Gst, GObject, Gtk

Instead of the 0.10 stuff.

Python-soya should just work if they didn't chance their api.
Well install the requirenments and run it and say to me then what error appears.

change the line in run_canta from/to:
#! /usr/bin/python -O
#! /usr/bin/python2 -O
So that it doesn't use python3 else you need to fix more stuff. 

The GST/GSTREAMER stuff should be the biggest problem, other than that it should probably just run.

**Comment by glixx** [comment]
canta
* Soya * Using 8 bits stencil buffer

* Soya * version 0.14
* Using OpenGL 3.0 Mesa 18.1.8
*   - renderer : Mesa DRI Intel(R) Sandybridge Desktop 
*   - vendor   : Intel Open Source Technology Center
*   - maximum number of lights        : 8
*   - maximum number of clip planes   : 8
*   - maximum number of texture units : 8
*   - maximum texture size            : 8192 pixels

None
Traceback (most recent call last):
  File "/usr/share/games/canta/run_canta", line 63, in <module>
    if __name__ == '__main__': main()
  File "/usr/share/games/canta/run_canta", line 61, in main
    CoreInit(window_title, APP_DIR)
  File "/usr/lib/python2.7/site-packages/canta/display/core_init.py", line 66, in __init__
    self._start()
  File "/usr/lib/python2.7/site-packages/canta/display/core_init.py", line 118, in _start
    self.theme_mgr.get_theme(self.theme_name, self.theme_dir)
  File "/usr/lib/python2.7/site-packages/canta/theme/theme_manager.py", line 35, in get_theme
    self.themes[theme_name] = Theme(self.parent_world, theme_dir, self.theme_cfg_file)
  File "/usr/lib/python2.7/site-packages/canta/theme/theme.py", line 65, in __init__
    self.create_models()
  File "/usr/lib/python2.7/site-packages/canta/theme/theme.py", line 235, in create_models
    self.debug)
  File "/usr/lib/python2.7/site-packages/canta/theme/static_model.py", line 84, in __init__
    material.texture = soya.Image.get(self.envmap)# The textured sphere map
  File "/usr/lib64/python2.7/site-packages/soya/__init__.py", line 283, in get
    return klass._alls.get(filename) or klass._alls.setdefault(filename, klass.load(filename))
  File "/usr/lib64/python2.7/site-packages/soya/__init__.py", line 389, in load
    image = open_image(file)
  File "image.pyx", line 28, in _soya.open_image
  File "image.pyx", line 46, in _soya.image_from_pil
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 699, in tostring
    "Please call tobytes() instead.")
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
* Soya3D * Quit...

**Comment by spiderbit** [comment]
You should use a newer version of soya3d it looks like the api of soya 0.14 is not in line with the PIL library on the system.
